# Generated by Django 4.0.4 on 2022-06-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_order_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
