# Generated by Django 4.0.4 on 2022-06-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
