# Generated by Django 4.0.4 on 2022-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
