# Generated by Django 4.0.4 on 2022-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='order_id',
        ),
        migrations.AddField(
            model_name='report',
            name='order_report',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
