# Generated by Django 4.0.4 on 2022-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_report_order_id_report_order_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vendor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
