# Generated by Django 4.0.4 on 2022-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_report_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='order_report',
        ),
        migrations.AddField(
            model_name='report',
            name='item_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='order_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
